# typed: false
# frozen_string_literal: true

# loop — terminal coding agent. Multi-provider, fast, native TUI.
#
# AUTO-GENERATED by the update-homebrew-tap job in notshekhar/loop's release.yml
# (.github/scripts/render-formula.py). Do not hand-edit — the next tag overwrites
# any changes to version/sha256. Edit the render script instead.
class Loop < Formula
  desc "Terminal coding agent — multi-provider, fast, native TUI"
  homepage "https://github.com/notshekhar/loop"
  version "0.5.5"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/notshekhar/loop/releases/download/v#{version}/loop-darwin-arm64.tar.gz"
      sha256 "3d867632a37016ebb7e89d224dd3c21ba84e955457a25321abf24c8bbbb2fb12"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/notshekhar/loop/releases/download/v#{version}/loop-linux-arm64.tar.gz"
      sha256 "c4f67351b9897c44404c9bd01f67848db011d77e4c9d10daa16cf2668b33fc0c"
    end
    on_intel do
      url "https://github.com/notshekhar/loop/releases/download/v#{version}/loop-linux-x64.tar.gz"
      sha256 "61be471059dd5ed4e6055884afae25f9a460acdfdde686a4660a1f221c0a5d88"
    end
  end

  def install
    # Tarball layout is <target>/{loop,package.json}; Homebrew chdirs into the
    # sole top-level dir. The binary reads its sidecar package.json via
    # dirname(execPath), so keep both together in libexec and symlink onto PATH
    # (execPath resolves through the symlink).
    libexec.install "loop", "package.json"
    bin.install_symlink libexec/"loop"
    bin.install_symlink libexec/"loop" => "agent"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/loop --version")
  end
end
