# typed: false
# frozen_string_literal: true

# loop — terminal coding agent. Multi-provider, fast, native TUI.
#
# AUTO-GENERATED by the update-homebrew-tap job in notshekhar/loop's release.yml
# (.github/scripts/render-formula.py). Do not hand-edit — the next tag overwrites
# any changes to version/sha256. Edit the render script instead.
class Loop < Formula
  desc "Terminal coding agent — multi-provider, fast, native TUI"
  homepage "https://github.com/notshekhar/loop"
  version "0.16.10"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/notshekhar/loop/releases/download/v#{version}/loop-darwin-arm64.tar.gz"
      sha256 "6fedf1a92b49f488280de3e26809e148cc884cfa15b4796c14855da1af6c9867"
    end
    on_intel do
      url "https://github.com/notshekhar/loop/releases/download/v#{version}/loop-darwin-x64.tar.gz"
      sha256 "3d31ebabbf716a95f4b4950c6f2a813fa48fa9e2b7a9f00796da7be51803e1d8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/notshekhar/loop/releases/download/v#{version}/loop-linux-arm64.tar.gz"
      sha256 "af16c8e44d986952e9e4a26e3b6e6d88d4cdc11431b113ec72becdfb2503f227"
    end
    on_intel do
      url "https://github.com/notshekhar/loop/releases/download/v#{version}/loop-linux-x64.tar.gz"
      sha256 "4df5e1a374892e85ba5d80b13b8b77ebe1bcbe2dc46fc4b947b04fa31995a76c"
    end
  end

  def install
    # Tarball layout is <target>/{loop,package.json}; Homebrew chdirs into the
    # sole top-level dir. The binary reads its sidecar package.json via
    # dirname(execPath), so keep both together in libexec and symlink onto PATH
    # (execPath resolves through the symlink).
    libexec.install "loop", "package.json"
    bin.install_symlink libexec/"loop"
    bin.install_symlink libexec/"loop" => "agent"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/loop --version")
  end
end
