# typed: false
# frozen_string_literal: true

# loop — terminal coding agent. Multi-provider, fast, native TUI.
#
# AUTO-GENERATED by the update-homebrew-tap job in notshekhar/loop's release.yml
# (.github/scripts/render-formula.py). Do not hand-edit — the next tag overwrites
# any changes to version/sha256. Edit the render script instead.
class Loop < Formula
  desc "Terminal coding agent — multi-provider, fast, native TUI"
  homepage "https://github.com/notshekhar/loop"
  version "0.13.2"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/notshekhar/loop/releases/download/v#{version}/loop-darwin-arm64.tar.gz"
      sha256 "42f336c99abd08adfe41e9e548cf55f8c2fda3d16c2fd8824f930eeacc292935"
    end
    on_intel do
      url "https://github.com/notshekhar/loop/releases/download/v#{version}/loop-darwin-x64.tar.gz"
      sha256 "218180ff505db793b8b4969334457c0dc595c986b928a5cca2c7a3acc5a86778"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/notshekhar/loop/releases/download/v#{version}/loop-linux-arm64.tar.gz"
      sha256 "8f2a679234f43ca8d0a8344620368122da480eb436ce5d64853ce8b350df4a2f"
    end
    on_intel do
      url "https://github.com/notshekhar/loop/releases/download/v#{version}/loop-linux-x64.tar.gz"
      sha256 "a3f9b5a6f0238d4a8bd58ae25f9593b8aff07503e52102158667c21deb601b86"
    end
  end

  def install
    # Tarball layout is <target>/{loop,package.json}; Homebrew chdirs into the
    # sole top-level dir. The binary reads its sidecar package.json via
    # dirname(execPath), so keep both together in libexec and symlink onto PATH
    # (execPath resolves through the symlink).
    libexec.install "loop", "package.json"
    bin.install_symlink libexec/"loop"
    bin.install_symlink libexec/"loop" => "agent"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/loop --version")
  end
end
